Console.Clear();
int a = 1;
int b = 8;
int c = 1985;
int d = 20;
int e = 6;
int max = a;
if (b > max) max = b ;
if (c > max) max = c ;
if (d > max) max = d ;
if (e > max) max = e ;
// System.Console.Write(max);
System.Console.Write("Вес самой тяжелой гири = ");
System.Console.Write(max);
System.Console.Write(" кг");
